### ISSUE TITLE
Decrease the MIN_SPEED to 0.2

### ISSUE THREAD

**Issue by lucidl** [thecodeofdaniel/UdemySpeedup#2]
Please, could you decrease the MIN_SPEED to 0.2 and update the extension? Sometimes I need to watch the material more carefully.
I tried to edit the addon (after unzipping the xpi file), but Firefox refused the new extension because of verification
and I don't need to sign-on my own extension where the only change is one digit.

Thank you.

**Comment by thecodeofdaniel** [comment]
Hello,

I've gone ahead and made a settings page where you can edit MIN_SPEED and whatnot. The lowest will be 0.0625 and the highest will be 16.  I'll try to publish the new version today :)

**Comment by thecodeofdaniel** [comment]
I've published the new version. Just click on the gear icon on the top right and it'll take you to the settings page. Then just edit the min speed and click "save settings"

**Comment by lucidl** [comment]
Thanks a lot.
